services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
    volumes:
      - "${LD_HOST_DATA_DIR}:/etc/linkding/data"
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    env_file:
      - .env
    restart: unless-stopped
