services:
  traggo:
    image: traggo/server:latest
    container_name: "${CONTAINER_NAME:-traggo}"
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TRAGGO_DEFAULT_USER_NAME=admin
      - TRAGGO_DEFAULT_USER_PASS=admin
    volumes:
      - "${HOST_DATA_DIR}:/opt/traggo/data"
    ports:
      - "${TRAGGO_PORT:-9091}:3030"
    env_file:
      - .env
